# Generated by Django 4.1 on 2022-08-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_projectimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimages',
            old_name='Project',
            new_name='project',
        ),
    ]
